### ISSUE TITLE
Font files have 755 permissions

### ISSUE THREAD

**Issue by desc** [roovenier/fonsta#4]
Hi.

We use fonsta since about 24 hours and our monitoring complains, that the downloaded font files are a kind of files which do not need to be executed, but they have executable file permissions.

Is it possible to adjust file permissions in lib/commands/install.js line 25 from '755' to '644'?

Regards,
  Dennis

**Comment by roovenier** [comment]
Hi, Dennis
Thank you for your note. I've updated the package.

**Comment by desc** [comment]
Works great for me.

Thank you Alexander.
